apiVersion: apps/v1
kind: Deployment
metadata:
  name: dsvpwa
  labels:
    app: dsvpwa
spec:
  selector:
    matchLabels:
      app: dsvpwa
  template:
    metadata:
      labels:
        app: dsvpwa
    spec:
      containers:
      - image: nitesh03/dsvpwa
        name: dsvpwa
        ports:
        - containerPort: 65413
