apiVersion: apps/v1
kind: Deployment
metadata:
  name: dsvpwa-deployment
  labels:
    app: dsvpwa
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dsvpwa
  template:
    metadata:
      labels:
        app: dsvpwa
    spec:
      containers:
      - name: dsvpwa:latest
        image: dsvpwa
        ports:
        - containerPort: 65413
